apiVersion: apps/v1
kind: Deployment
metadata:
  name: aleksserver
  labels:
    app: aleksserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aleksserver
  template:
    metadata:
      labels:
        app: aleksserver
    spec:
      containers:
      - name: aleksserver
        image: aleksnd19/assignment
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: aleksserver
  labels:
    tier: front-end
spec:
  containers:
  - name: nginx
    image: aleksnd19/assignment
    ports:
    - containerPort: 80
